CREATE TABLE Q_PERSON 
(
  ID NUMBER NOT NULL 
, Q_STATE_ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, SURNAME VARCHAR2(300 BYTE) 
, Q_PERSON_ID VARCHAR2(20 BYTE) 
, BARCODE VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT Q_PERSON_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX Q_PERSON_PK ON Q_PERSON (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE INDEX Q_PERSON_Q_STATE_ID_INDX ON Q_PERSON (Q_STATE_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE Q_PERSON
ADD CONSTRAINT Q_PERSON_Q_STATE_ID_FK FOREIGN KEY
(
  Q_STATE_ID 
)
REFERENCES Q_STATE
(
  ID 
)
ENABLE;

COMMENT ON COLUMN Q_PERSON.Q_PERSON_ID IS 'If person has multiple citizenship, this is parent citizenship';
